name: Sync Files to Other Repos

on: 
  push:
    paths:
      - '.gitignore'
      - '.gitattributes'

jobs:
  sync-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [GameCraftGuild/Unity-Package-Template]
      include:
        - files: '.gitattributes .gitignore'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push files
        uses: mitchkm/copy_file_to_another_repo_action@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: ${{ matrix.files }}
          destination_repo: ${{ matrix.repo }}
          destination_folder: '.'
          user_email: 'mitchkm21@gmail.com'
          user_name: 'mitchkm'
