name: Push files to GameCraftGuild/Unity-Package-Template

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push files
        uses: mitchkm/copy_file_to_another_repo_action@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '.gitattributes .gitignore'
          destination_repo: 'GameCraftGuild/Unity-Package-Template'
          destination_folder: '.'
          user_email: 'mitchkm21@gmail.com'
          user_name: 'mitchkm'
