name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push files to GameCraftGuild/Unity-Package-Template
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: './.gitattributes :./.gitignore'
          use_rsync: 'true'
          destination_repo: 'GameCraftGuild/Unity-Package-Template'
          destination_folder: '.'